services: 
  challenge-app: 
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/usr/src/app/output
      - ./analysis_results:/usr/src/app/analysis_results
    restart: no
        